Homepage layout proposal
Gothic-Modding-Community/gmc pull request #116
Opened 2024-06-02 16:25 UTC by muczc1wek

2024-06-03 10:41 UTC, piotrmacha requested changes

2024-06-03 10:41 UTC, piotrmacha commented on docs/index.md
> +    [:octicons-arrow-right-24: GitHub](https://github.com/Silver-Ore-Team/zBassMusic)
Change the repo link to GMC

2024-06-03 16:23 UTC, muczc1wek commented
![obraz](https://github.com/Gothic-Modding-Community/gmc/assets/110698397/6f4b114d-c8e8-4127-914d-f9f9a6a129cc)

2024-06-06 18:35 UTC, muczc1wek commented
I think the PR is ready, I would also provide polish translation, just let me know if the layout is good enough

2024-06-07 16:03 UTC, kamilkrzyskow requested changes

2024-06-07 16:03 UTC, kamilkrzyskow commented on docs/zengin/index.md
> +    Learn how to create plugins with Union SDK, a community software development kit for ZenGin.
community-made would be more correct, there is no pro version of union

2024-06-07 16:05 UTC, kamilkrzyskow commented
Additionally, the position of the links isn't synced to the bottom, I once helped out with this via extra CSS, should be a small fix 🤔 
Will edit the comment in a bit when I find it....

2024-06-07 16:14 UTC, kamilkrzyskow commented
Otherwise the layout and content seems fine, you can start translating imo 👌

2024-06-07 16:20 UTC, kamilkrzyskow requested changes

2024-06-07 16:20 UTC, kamilkrzyskow commented on docs/index.md
> +    [:octicons-arrow-right-24: How to Contibute](./contribute/index.md)
The `./` is still here

2024-06-07 16:24 UTC, muczc1wek commented
@kamilkrzyskow  Is that what you wanted to achieve?
![obraz](https://github.com/Gothic-Modding-Community/gmc/assets/110698397/f8f5575c-65a7-4490-8eb8-4668136281ed)

2024-06-07 16:25 UTC, kamilkrzyskow commented
Yes, the links are on the bottom even if the content isn't as big as in the other column. 
Everything is "unified" for lack of a better word.

2024-06-07 16:26 UTC, muczc1wek commented on docs/index.md
> +    [:octicons-arrow-right-24: How to Contibute](./contribute/index.md)
Yeah I accidentally deleted it in zengin/index not index 😄

2024-06-07 16:33 UTC, muczc1wek commented
I am currently connected with my PC by remote desktop so the graphics is a bit deformed

2024-06-07 16:35 UTC, kamilkrzyskow commented
The changes LGTM, good CSS placement 👍 , the `outline` comment didn't have to be there though.
I forgot to remove it from the answer, this was for me to figure this solution out 😅

2024-06-07 16:43 UTC, kamilkrzyskow commented
Please also add this

https://github.com/Gothic-Modding-Community/gmc/assets/34622465/d3996056-c092-41d0-97aa-2acda821230a

```css
.grid.cards li > p:first-child > strong {
  vertical-align: middle;
}
```

2024-06-07 16:52 UTC, kamilkrzyskow requested changes

2024-06-07 16:52 UTC, kamilkrzyskow commented on docs/zengin/index.pl.md
> +    [:octicons-arrow-right-24: Getting Started](union/sdk/getting_started.md)
Link names should be localized even though the pages aren't localized yet.

2024-06-07 16:54 UTC, muczc1wek commented on docs/zengin/index.pl.md
> +    [:octicons-arrow-right-24: Getting Started](union/sdk/getting_started.md)
Yeah, i noticed that too

2024-06-07 17:05 UTC, kamilkrzyskow requested changes

2024-06-07 17:05 UTC, kamilkrzyskow commented on docs/zengin/index.pl.md
> +    [:octicons-arrow-right-24: Scripts](scripts/index.md)
English name

2024-06-07 17:08 UTC, muczc1wek commented on docs/zengin/index.pl.md
> +    [:octicons-arrow-right-24: Scripts](scripts/index.md)
I will fix that later, I need some rest from pc

2024-06-07 21:20 UTC, kamilkrzyskow approved these changes

2024-06-07 21:21 UTC, merged