[Tools] Daedalus Language Server article
Gothic-Modding-Community/gmc pull request #121
Opened 2024-06-16 11:48 UTC by muczc1wek

2024-06-16 13:38 UTC, piotrmacha requested changes
One comment related to proper casing of names. The rest is fine.

2024-06-16 13:38 UTC, piotrmacha commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +[Daedalus Language Server](https://github.com/Kirides/DaedalusLanguageServer) is a language server for gothic's scripting language - daedalus, created by [Kirides](https://github.com/kirides). Howeve
Casing:
* `gothic's` -> `Gothic's`
* `daedalus` -> `Daedalus`

2024-06-16 14:01 UTC, piotrmacha approved these changes

2024-06-21 23:29 UTC, kamilkrzyskow commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +    "daedalusLanguageServer.fileEncoding": "Windows-1250",
Based on the code it should also allow for a lowercase `windows-1250`.
https://github.com/kirides/DaedalusLanguageServer/blob/f67a464ffd56fc37c932f456edddf5947b8efe1b/langserver/parseresultsmanager.go#L63

There is also the initial value of `1252` without the windows part 🤔 
https://github.com/kirides/DaedalusLanguageServer/blob/f67a464ffd56fc37c932f456edddf5947b8efe1b/langserver/lsphandler.go#L64-L65

Maybe `windows1250` could work if `1252` works 😆 I'm sure there is a nice error message if the encoding is unrecognized, but would be nice of Kirides to allow all variants 🥹

2024-06-21 23:29 UTC, kamilkrzyskow commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +    This article is focused on a vscode-daedalus extension, but since DLS uses [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) it could be implemented into other edi
*the vscode-daedalus

2024-06-22 17:52 UTC, muczc1wek commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +    "daedalusLanguageServer.fileEncoding": "Windows-1250",
So what should I change in the guide?

2024-06-22 17:53 UTC, muczc1wek commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +    This article is focused on a vscode-daedalus extension, but since DLS uses [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) it could be implemented into other edi
In both occurrences or only in the warning?

2024-06-22 19:19 UTC, kamilkrzyskow commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +    "daedalusLanguageServer.fileEncoding": "Windows-1250",
I didn't mark this "review" as a request for changes, you can keep it as-is.

Just an observation for you guys to maybe move upstream to kirides.
From an UX standpoint being able to just set `windows1250` everywhere without the `-` as an exception would be better. 
Don't know about DX, as perhaps using same settings between projects is better and the guide depicts some sort of standard in the "Gothic developer space".

2024-06-22 19:24 UTC, kamilkrzyskow commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +    This article is focused on a vscode-daedalus extension, but since DLS uses [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) it could be implemented into other edi
Only this one in the warning instead of "a vscode-daedalus", the previous one has `named` before and the other one has `the` before. We're using `the` as the guide speaks about **the** specific extension, not **a** plugin of the `vscode-daedalus` _type_.

2024-06-22 20:48 UTC, muczc1wek commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +    "daedalusLanguageServer.fileEncoding": "Windows-1250",
First of all, the plugin should automatically set the encoding of daedalus. It confuse people all the time

2024-06-22 20:57 UTC, muczc1wek commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +    "daedalusLanguageServer.fileEncoding": "Windows-1250",
Looks like Auronen tried to do something with that https://github.com/kirides/vscode-daedalus/issues/9

2024-07-24 09:39 UTC, merged