[Textures] New main article
Gothic-Modding-Community/gmc pull request #124
Opened 2024-06-21 21:16 UTC by muczc1wek

2024-06-21 22:52 UTC, kamilkrzyskow requested changes

2024-06-21 22:52 UTC, kamilkrzyskow commented on docs/zengin/textures.md
> +    Technical description of the `.TEX` texture format can be found in the [ZenKit documentaion](https://zk.gothickit.dev/engine/formats/texture/).
documentaion

2024-06-21 22:52 UTC, kamilkrzyskow commented on docs/zengin/textures.md
> +[GitHub](https://gitlab.com/Shoun2137/ztexipy)
GitHub

2024-06-21 22:52 UTC, kamilkrzyskow commented on docs/zengin/textures.md
> +There are some tools created by community, that simplify working with ZenGin textures.
by community

2024-06-21 22:52 UTC, kamilkrzyskow commented on docs/zengin/textures.md
> +Latest tool, developed by [Shoun](https://gitlab.com/Shoun2137). Offers batch conversion, an intuitive viewer, and Windows context menu shortcuts.
Weird that it's the only tool with the author mentioned, do we have favouritism, for our saviour Shoun? 😆 
Maybe mention it has Linux support, I think the other tools require wine 🤔

2024-06-21 22:56 UTC, kamilkrzyskow commented on docs/zengin/textures.md
> +[Thread on WoG](https://forum.worldofplayers.de/forum/threads/1601349-Tool-GoTex)
In case WoG dies on us, we should include the link to his GitHub too.

2024-06-22 07:56 UTC, muczc1wek commented on docs/zengin/textures.md
> +Latest tool, developed by [Shoun](https://gitlab.com/Shoun2137). Offers batch conversion, an intuitive viewer, and Windows context menu shortcuts.
No, i simply don't know the authors of other tools 😁 But that's a good point

2024-06-22 07:58 UTC, muczc1wek commented on docs/zengin/textures.md
> +There are some tools created by community, that simplify working with ZenGin textures.
Hmm? There is no typo here

2024-06-22 11:42 UTC, kamilkrzyskow commented on docs/zengin/textures.md
> +There are some tools created by community, that simplify working with ZenGin textures.
Add a word/s between to make it less dry when reading.

By the community 
By our community 
By the Gothic community
etc.
or change the structure and use synonyms 👌

2024-07-02 08:52 UTC, auronen commented
We could add a link to [GRM Blogpost](https://www.gothic-reloaded-mod.org/en/blog/more-than-a-texture-patch-2) about mipmaps, it demonstrates it well.

2024-07-23 15:44 UTC, kamilkrzyskow commented
OK, I'll have a look

2024-07-23 18:52 UTC, kamilkrzyskow requested changes

2024-07-23 18:52 UTC, kamilkrzyskow commented on docs/zengin/textures/32bit_texture.md
> +By default ZenGin supports only compresed `DXT1` and `DXT3` textures. [zSurface32 patch](https://worldofplayers.ru/threads/43009/page-3#post-1180504), created by Gratt improves texture quality by add
compresed -> compressed

2024-07-23 18:52 UTC, kamilkrzyskow commented on docs/zengin/textures/32bit_texture.md
> +    It is advised to use `BGRA8888` due to performance reasons, as other colorspaces require additional conversion at runtime.
colorspaces -> color spaces
colorspace -> color space
find all occurrences that I didn't mark :v:


?Maybe link to wikipedia when first time referencing a color space https://en.wikipedia.org/wiki/RGBA_color_model
Maybe there is some benchmark between their performance? 🤔

2024-07-23 18:52 UTC, kamilkrzyskow commented on docs/zengin/textures/32bit_texture.md
> +    - Set the `Colorspace` to `BGRA8888 (zEnum:3)` or other supported format.
Is the setting still written as one word in the current program? If so, I'll contact Shoun about it 🤔 
For now keep it.

2024-07-23 18:52 UTC, kamilkrzyskow commented on docs/zengin/textures/32bit_texture.md
> +![Ingame Example](../../assets/images/EXAMPLE_INGAME.WEBP)
In-game

Also modify the images that are too big with attr_list. 
Example from Union Getting Started `{: style='min-width: 0;' }`
Or something similar

2024-07-23 18:52 UTC, kamilkrzyskow commented on docs/zengin/textures/32bit_texture.md
> +    DXT3 shows noticible banding throughout entire texture wherever there's alpha channel, while BGRA8888 has smooth gradient transition.
noticible -> noticeable

2024-07-23 18:52 UTC, kamilkrzyskow commented on docs/zengin/textures/index.md
> +    Technical documentaion of the `.TEX` texture format can be found in the [ZenKit documentaion](https://zk.gothickit.dev/engine/formats/texture/).
documentaion -> documentation

2024-07-23 18:52 UTC, kamilkrzyskow commented on docs/zengin/textures/index.md
> +Textures are pictures that get projected onto 3D models and on a 2D user interface in the game. ZenGin uses its own texture format `.TEX`, that in fact is a container for the texture in one of availa
wrap `in fact` between commas, or replace it with some other word

2024-07-23 18:52 UTC, kamilkrzyskow commented on docs/zengin/textures/index.md
> +By default, `.tga` files with a proper resolution are converted to `.TEX` files by the engine, when they appear in the game or a game is started with `-convertall` parameter. Also, you can convert te
.tga all other are uppercase, so it should match

2024-07-23 18:52 UTC, kamilkrzyskow commented on docs/zengin/textures/32bit_texture.md
> +[Source comparison files are available here.](../../assets/EXAMPLE_SOURCE.7z)
I'm not really a fan of the all caps files, but I see you copied it from the original article.
It's ok if you want to maintain the structure, but it's not the same here, as the original has
`assets/32bit-texture-support/STEP_1.WEBP` - a clear separation from other assets via the directory,
However, here you just put it in the `assets/` or `assets/images` without changes in names.

This needs a fix, I would change the name of the files, but you can create a subdirectory.
`assets/other/32bit-texture-support/EXAMPLE_SOURCE.7z`
`assets/images/32bit-texture-support/STEP_1.WEBP`
`assets/images/32bit_texture_support_STEP_1.WEBP`
`assets/examples/32bit_texture_support.7z`

Choose your favorite or improve it even more :v:

2024-07-23 18:52 UTC, kamilkrzyskow commented on docs/zengin/textures/32bit_texture.md
> +    ![Comparison between BGRA8888 vs DXT3 (Alpha)](../../assets/images/EXAMPLE_1.WEBP)
Use attr_list to force a white background for the image to showcase the gradient better.

2024-07-24 09:49 UTC, muczc1wek commented on docs/zengin/textures/index.md
> +By default, `.tga` files with a proper resolution are converted to `.TEX` files by the engine, when they appear in the game or a game is started with `-convertall` parameter. Also, you can convert te
I wouldn't agree with taht. `.TEX` is a exception, since it is uppercase almost every time, unlike formats like `.tga`, `.jpg` etc.

2024-07-24 09:50 UTC, muczc1wek commented on docs/zengin/textures/index.md
> +By default, `.tga` files with a proper resolution are converted to `.TEX` files by the engine, when they appear in the game or a game is started with `-convertall` parameter. Also, you can convert te
I wouldn't agree with taht. .TEX is an exception, since it is uppercase almost every time, unlike formats like .tga, .jpg etc.

2024-07-24 09:56 UTC, muczc1wek commented on docs/zengin/textures/32bit_texture.md
> +![Ingame Example](../../assets/images/EXAMPLE_INGAME.WEBP)
Which images are too big?

2024-07-24 09:59 UTC, kamilkrzyskow commented on docs/zengin/textures/index.md
> +By default, `.tga` files with a proper resolution are converted to `.TEX` files by the engine, when they appear in the game or a game is started with `-convertall` parameter. Also, you can convert te
True, hmm. So perhaps instead of focusing on the file extension, which is only a part of the filename, we should use the image format names, then everything will be in caps TGA, TEX etc. 🤔, but it's up to you. If you think the extensions are better to describe the compilation process, then keep it as is ✌️

2024-07-24 10:42 UTC, kamilkrzyskow commented on docs/zengin/textures/32bit_texture.md
> +![Ingame Example](../../assets/images/EXAMPLE_INGAME.WEBP)
I missed this notification, probably got merged with the other message.

> Which images are too big?

Those that take up too much vertical sapce on my 1080p monitor and don't have fine details that require the bigger size🤔So this is yet another subjective issue hmm. So you can keep the sizing for now as is. I'll think about a more general CSS change, as currently the issue is the `min-width: 75%` in the `.md-content img` override. Small images explode in size to keep the aspect ratio.

If you want, you can also play around with it, removing that min-width, and replace it with a combination of min-height, max-height using `rem` values. Like:
```css
min-height: 8rem;
max-height: 20rem;
```
but perhaps there is no optimal solution for this, and some images will still have to be adjusted with attr_list.
If you decide to change the CSS, be sure to check other pages with images like C_ITEM.

2024-08-04 10:14 UTC, kamilkrzyskow approved these changes

2024-08-04 10:43 UTC, merged