Update `scripts/index` and gothic sourcer article
Gothic-Modding-Community/gmc pull request #135
Opened 2024-07-30 18:04 UTC by muczc1wek

2024-08-04 11:08 UTC, kamilkrzyskow commented
The language server is AFAIK tool agnostic, it's not bound to VS Code, but the extension using the language server is.
I also think if there are alternative tools to some aspects of Gothic Sourcer, then the article should have an opinionated comment about this, but I don't know about alternative 😆

2024-08-08 14:39 UTC, muczc1wek commented
> The language server is AFAIK tool agnostic, it's not bound to VS Code, but the extension using the language server is.


So how should I put this? I know dls != vscode-daedalus but for the regular user these things are the same

2024-08-08 20:56 UTC, kamilkrzyskow commented
Perhaps they're seen as the same, but docs should strive for factuality. Of course there are some opinionated takes here or there, but there should be a good reason for those.

Here instead of "Also known as Daedalus Language Server", for example change it to "The VS Code extension acts as a proxy for the [Daedalus Language Server](https://github.com) to provide [list of features]" or "The VS Code extension provides [list of features] and uses [Daedalus Language Server](https://github.com) as the back-end for them." etc. maybe ChatGPT has something better.

2024-10-12 13:02 UTC, kamilkrzyskow requested changes

2024-10-12 13:02 UTC, kamilkrzyskow commented on docs/zengin/scripts/index.md
> +[:octicons-arrow-right-24: Read More](../tools/daedalus_tools/daedalus_language_server.md)
The section title `###` mentions VS Code Extension, but the link for Read More is for the Language Server 🤔 
So maybe re-structure the paragraph to say "The Daedalus Language Server provides syntax [...], and it is used by the VS Code extension."

But now this "short" excerpt is more explicit than the actual `daedalus_language_server.md` file 😆 
So it's hard to say how to structure it properly

2024-10-12 13:12 UTC, muczc1wek commented on docs/zengin/tools/gothic_sourcer.md
> +You can download the latest version of Gothic Sourcer from the [Resource Manager](https://worldofplayers.ru/threads/41942/).
I think there is an installer on gratt's gdrive

2024-10-12 13:16 UTC, muczc1wek commented on docs/zengin/scripts/index.md
> +[:octicons-arrow-right-24: Read More](../tools/daedalus_tools/daedalus_language_server.md)
The dls article is mostly about vscode-daedalus. I don't see a reason to not link to it in "read more"

2024-10-12 13:38 UTC, kamilkrzyskow commented on docs/zengin/scripts/index.md
> +[:octicons-arrow-right-24: Read More](../tools/daedalus_tools/daedalus_language_server.md)
OK, then perhaps there is no need for the DLS link to GitHub, as it's in the Read More article, or add the extension link here as well to make it more synced.

2024-10-13 19:08 UTC, muczc1wek commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +[Daedalus Language Server](https://github.com/Kirides/DaedalusLanguageServer) is a language server for Gothic's scripting language - Daedalus, created by [Kirides](https://github.com/kirides). Howeve
I will leave it as it is

2024-10-13 19:34 UTC, kamilkrzyskow commented on docs/zengin/tools/daedalus_tools/daedalus_language_server.md
> +[Daedalus Language Server](https://github.com/Kirides/DaedalusLanguageServer) is a language server for Gothic's scripting language - Daedalus, created by [Kirides](https://github.com/kirides). Howeve
Fine. Still, there should be a clear separation between the extension and the DLS imo, but this section can be improved later when more text editors incorporate the Language Server etc.

2024-10-13 19:36 UTC, kamilkrzyskow approved these changes

2024-10-13 19:38 UTC, kamilkrzyskow commented
LGTM, nice work on the preservation of the Gothic Sourcer in a separate repository 👍 
You can squash merge when you want :v:

2024-10-13 19:57 UTC, merged