[Animation] Update & reword "How to play or edit animations" to be a bit more specific
Gothic-Modding-Community/gmc pull request #137
Opened 2024-10-04 19:30 UTC by the-overdriven

I’d like to suggest some rewording in Standalone animation doc to enhance clarity and accuracy:
- reword "How to play or edit animations" note to be a bit more specific and visible (avoid "it" and "this" words)
- update tool name (in latest KrxImpExp it's "Shoun's ASCII Model importer", not Kerrax)

2024-10-04 19:34 UTC, Shoun2137 commented
There's only one module that's written by me, it should be neutral like imo `zengin's ASCII Model Importer`

2024-10-04 19:41 UTC, the-overdriven commented
I mean the name that's in Blender under File -> Import:
![image](https://github.com/user-attachments/assets/efd07549-11cd-42eb-84fe-af9a53f2b568)
I don't have a preference for who is listed as the author, but the docs should consistently use the same name to make it easier to find and to avoid confusion.

2024-10-04 19:53 UTC, Shoun2137 commented
ah, this shit, that explains it lol

2024-10-05 16:13 UTC, kamilkrzyskow requested changes

2024-10-05 16:13 UTC, kamilkrzyskow commented on docs/zengin/anims/tutorials/standalone_animation.md
>  Gothic characters are modular and you can change their heads on the fly, even during gameplay as seen in this amazing video from my dear friend and colleague Fawkes - [Head changing](https://www.yout
This line also includes the `Import > Kerrax ASCII model` version. I'm not so sure it has to be so specific hmm.

Also the article doesn't have any info about the KrxImpExp plugin, it just expects the readers to already know about it and have installed it in Blender, and tells the user to choose the options 🤔 Perhaps the written text is connected with some other youtube video where it's shown in a better way, but the text should be disconnected from the video.

So please fix it overall in a way that hints the user about the need to install some sort of plugin to import the ASC files into Blender, and currently it's the KrxImpExp (internal ref link to the KrxImpExp tool page), and perhaps instead of being specific about the option name, add a screenshot with possible context menu option `File > Import > All KrxImpExp options` and later tell the readers "Import the ASC"

2024-10-05 16:15 UTC, kamilkrzyskow commented
@the-overdriven 
Also worth noting this page will be moved later on to the blog structure :v:
So perhaps it will be further improved during that process🤔

2024-10-06 14:02 UTC, the-overdriven commented on docs/zengin/anims/tutorials/standalone_animation.md
>  Gothic characters are modular and you can change their heads on the fly, even during gameplay as seen in this amazing video from my dear friend and colleague Fawkes - [Head changing](https://www.yout
You overestimate me 😉 I only wanted to slightly improve the note for playing and editing animations in this PR. And only in the terms of wording, not content. I don't feel too experienced to write about animations. Maybe let's move it to TODO and do in a separate PR?

The KrxImpExp plugin is already mentioned on [the first page](https://gothic-modding-community.github.io/gmc/zengin/anims/), that is fine IMO. In general, the rest of the article is also fine. What I really miss is a more basic example. The current one seems like it's trying to cover everything, and that approach has a downside that it makes it too overwhelming for beginners. But I digress.

2024-10-06 14:08 UTC, the-overdriven commented on docs/zengin/anims/tutorials/standalone_animation.md
> +!!! How to play or edit animations
Done.

2024-10-06 15:49 UTC, kamilkrzyskow commented on docs/zengin/anims/tutorials/standalone_animation.md
>  Gothic characters are modular and you can change their heads on the fly, even during gameplay as seen in this amazing video from my dear friend and colleague Fawkes - [Head changing](https://www.yout
OK, fine by me. But in general GMC proves the quote about "Nothing is more permanent than a temporary solution." 😆

2024-10-06 15:52 UTC, kamilkrzyskow commented
LGTM 👍  The PR is a fixup, so I don't think there is a need for other reviews.

2024-10-06 15:54 UTC, merged