[Meshes] Portals article (WIP)
Gothic-Modding-Community/gmc pull request #139
Opened 2024-10-14 12:29 UTC by muczc1wek

Content is ready but I need better images 😞 

[Demo](https://muczc1wek.github.io/gmc/zengin/meshes/portals/)

2024-11-11 17:22 UTC, kamilkrzyskow requested changes

2024-11-11 17:22 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +Outdoor portals materials have followning naming convention:
typo followning -> following

2024-11-11 17:22 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +All materials of portal type, have to start with `P:` or `PN:`, the difference between each of them is only in game engine, `PN:` stands for Portal NonFading, and`P:` stands for Portals and if player
> then opacity of near portals will increase.

when a player is close to the portal then it becomes more transparent,
so the opacity decreases

2024-11-11 17:22 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +    Material names with the prefix `PN:` (“N” for NoFade) “open” visually as the camera approaches, but do not fade out like the other `P:` portals. This makes sense, for example, if there is a textu
> “N” for NoFade) “open”

What are those weird \“ they're not normal ", are we using them anywhere else in the docs?

2024-11-11 17:22 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +    Material names with the prefix `PN:` (“N” for NoFade) “open” visually as the camera approaches, but do not fade out like the other `P:` portals. This makes sense, for example, if there is a textu
Can you provide a specific example in base game either G1/G2 of such portals? Even if we can't provide two different images, then it would make it easier to understand when to use which. Me as a non-modder / "less than beginner" I don't understand why it makes sense when a portal has an alpha channel .

2024-11-11 17:22 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +For every portal, 2 materials have to be created - one for each direction. Their names have to be set in proper order. First name `Front` is always place or room to which you are entering from, and s
A bit overly complex. 
For every portal, 2 materials have to be created - one for each direction. Their names have to match the direction they're facing. For example, the portal for entering room 2 from room 1 should be named `P:room1_room2`. And vice versa the second portal to go back from room 2 to room 1 should be named `P:room2_room1`.

2024-11-11 17:22 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +In addition, the empty string `""` is used to mark the portal to the outside world. For example, if you are entering corridor 1 from the outside world, then you need to name portal `P:corridor1_`. If
Names don't match with the explanation above and the image below, could be a bit shorter or even a bullet point list 🤔 
In addition, a blank string `""` is used to refer to the outside world. For example, if you are entering corridor 1 from the outside world, then you need to name portal `P:_corridor1`. If you want to go back from corridor 1 to the outside world, then you need to name portal `P:corridor1_`.

2024-11-11 17:22 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +Also the polys inside the sector must be connected to the walls of the setor. If some polys will be floating in the air, the engine could not render them properly.
typo setor -> sector

2024-11-11 17:22 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +![](../../assets/images/portals/outdoor_modeling3.JPG)
JPG 🤔 while all other are png

2024-11-11 17:22 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +Ghostoccluders are polys in outdoor levels that have a material called `GHOSTOCCLUDER`. Such polygons are not displayed in the game, but serve to mask areas of the level that are unnecessary for visu
> polys  do

two spaces 😁

2024-11-11 17:22 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +[^1]: Inspired by the article about potrals from [Gothic Editing Wiki](https://wiki.worldofgothic.de/doku.php?id=zengin:portale)
typo potrals -> portals

2024-11-11 17:25 UTC, kamilkrzyskow commented
The list at the end also seems overly complex, but here is my limit, I don't know how to simplify it 😢 
Once you resolve my comments, then request auronen for review 😆 

Also how to check if the portal is working other than, you know, looking at it, not seeing it etc.
Is there a way to get a log message when a portal doesn't work according to the engine, or does the engine not keep track of such things.

2024-11-11 19:22 UTC, muczc1wek commented on docs/zengin/meshes/portals.md
> +    Material names with the prefix `PN:` (“N” for NoFade) “open” visually as the camera approaches, but do not fade out like the other `P:` portals. This makes sense, for example, if there is a textu
Well it is copy-paste from Gothic Editing Wiki, but I will try

2024-11-11 19:25 UTC, muczc1wek commented
> Also how to check if the portal is working other than, you know, looking at it, not seeing it etc?

I think if the portal doesn't work it A - couldn't be passed B - provide weird graphic glitches

2024-11-11 19:57 UTC, muczc1wek commented on docs/zengin/meshes/portals.md
> +![](../../assets/images/portals/outdoor_modeling3.JPG)
Is it a problem? I could convert it but i don't see a reason for doing this

2024-11-11 20:11 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +![](../../assets/images/portals/outdoor_modeling3.JPG)
It's not a problem. Just like the comment about the two spaces gap in the text below, it's more of a nitpick.
However, thinking long term, as in, future-proofing the docs it might be better to keep the photos in PNG format.
But they can always be changed later on when the time is right. 🤷 
https://squidfunk.github.io/mkdocs-material/plugins/requirements/image-processing/#pngquant

2024-11-11 20:17 UTC, kamilkrzyskow commented on docs/zengin/meshes/portals.md
> +For every portal, 2 materials have to be created - one for each direction. Their names have to be set in proper order. First name `Front` is always place or room to which you are entering from, and s
@muczc1wek 
It struck me now, that I don't know from where are those room 1, room 2 names coming from?
Is this some Spacer object id, or what? Also worth adding to showcase the connection.

2024-11-12 14:02 UTC, muczc1wek commented on docs/zengin/meshes/portals.md
> +For every portal, 2 materials have to be created - one for each direction. Their names have to be set in proper order. First name `Front` is always place or room to which you are entering from, and s
These are only example names taken from the image below

2025-01-05 22:41 UTC, kamilkrzyskow approved these changes

2025-01-11 20:36 UTC, merged