Polish translations of Ikarus and LeGo articles (except FrameFunctions)
Gothic-Modding-Community/gmc pull request #67
Opened 2023-01-25 10:28 UTC by Emu-git

Merge after HRY language support

2023-01-26 09:00 UTC, kamilkrzyskow requested changes
I found some issues. Please look over them.

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +- `return` - wartość opcji w posatci zmiennej string, albo pustą zmienną gdy opcja nie istnieje w danej sekcji
`posatci` typo again

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +- `return` - wartość opcji w posatci zmiennej string, albo pustą zmienną gdy opcja nie istnieje w danej sekcji
`posatci` typo, best to scan the file with some dictionary software, even a browser text area should suffice.

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +Sparwdza czy dana sekcja istnieje w `Gothic.ini`
`Sparwdza` typo again

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +- `return` - `TRUE` jeśli skecja istnieje, `FALSE` w każdym innym przypadku
`skecja` typo again

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +Sparwdza czy dana sekcja istnieje w ini załadowanej modyfikacji
`Sparwdza`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +- `return` - `TRUE` jeśli skecja istnieje, `FALSE` w każdym innym przypadku
`skecja`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +- `return` - `TRUE` jeśli skecja istnieje, `FALSE` w każdym innym przypadku
`skecja`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +- `sectionname` - nazwa przeszukiwaniej sekcji
`przeszukiwaniej`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +- `sectionname` - nazwa przeszukiwaniej sekcji
`przeszukiwaniej`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +- `return` - `TRUE` jeśli skecja istnieje, `FALSE` w każdym innym przypadku
`skecja`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/ikarus/ini_access.pl.md
> +    Jeśli wprowadzasz nowe opcje, najlepiej kierować się paroma zasadami. Dobrą praktyką jest nazywanie swoich opcji tak aby inni mogli je zrozumieć i umieszczanie ich w sekcji o takiej samej nazwie
`sowjej`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +# Bars
Better add a translation after a dash. I understand why you kept `Bars` as it's an universal searchable word.

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +## inicjalizacja
Small letter

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +Ustawia texture wartości paska.
`texture`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +- `texture` - nowa textura
`textura`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +Ustawia texture tła paska.
`texture`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +- `texture` - nowa textura
`textura`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +### A dedicated experience bar
Translation missing.

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +    var string backTex; // Textura tła
`Textura`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +    var string barTex;  // Textura wartości paska
`Textura`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +Stwórz nową instancje z pomocą GothicBar i zmień tylko pozycję. Oczywiście dodaj też pętlę za pomocą pakietu FrameFunctions.
GothicBar isn't in code `GothicBar`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/console_commands.pl.md
> +# Console Commands
Same as with `Bars` better add a translation after a dash.

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/console_commands.pl.md
> +- f - Ta funkcja zostanie usunięta, a powiązane z nią polecenie przestanie działać.
f is not in code `f`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/console_commands.pl.md
> +const string Wersja = "Wersja modyfikacji - 0.1alpha";
Better to avoid naming variables with anything other than English, to assure that people won't do so in their own projects. However, I understand this is debatable 🤔 .

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/console_commands.pl.md
> +    // eszta kodu
`eszta`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/gamestate.pl.md
> +# Gamestate
Same situation as with `Bars`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/gamestate.pl.md
> +## Zależnośći
`Zależnośći`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/gamestate.pl.md
> +- `listener` - usuwana funkcja listenera.
Bad grammar? I think something along the lines of "listener do usunięcia" would be better.

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/gamestate.pl.md
> +## Examples
Translation missing.

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/gamestate.pl.md
> +Ten przykład nie wymaga więkrzych wyjaśnień.
`więkrzyc`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +    Jest to tłumaczenie artykułu napisanego oryginalnie przez Gottfrieda i Lehone i umieszczonego w oficjalnej [dokumentacji](https://lego.worldofplayers.de/?Beispiele_Bars) pakietu LeGo
Missing dot at the end.

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/index.pl.md
> +| Autor   | [:material-badge-account-horizontal: Lehona, Gottfried & contributors](https://github.com/Lehona/LeGo/graphs/contributors) |
`& contributors` not translated.

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/index.pl.md
> +    Kod LeGo jest hostowany na [GitHubie](https://github.com/Lehona/LeGo), a sam pakiet skryptowy ma własną [strone z dokumentacją](https://lego.worldofplayers.de/) (niestety tylko w wersji niemiecki
There is no need for such additions like "(niestety tylko w wersji niemieckiej)."

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/item_helper.pl.md
> +# ItemHelper
Same as with `Bars`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/misc.pl.md
> +- `sine` - cosinus kąta
`sine` instead of `cosine`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/misc.pl.md
> +- `x2` - współrzędna x dógiego punktu
`dógiego`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/misc.pl.md
> +- `y2` - współrzędna y drógiego punktu
`drógiego`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/misc.pl.md
> +Oblicza odległość między dwoma punktami na płaszczyźnie dwuwymiarowej, jako Ikarusowy `floats`
`floats` instead of `float`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/misc.pl.md
> +- `x2` - współrzędna x dógiego punktu
`dógiego`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/misc.pl.md
> +- `y2` - współrzędna y drógiego punktu
`drógiego`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/talents.pl.md
> +# Talents
Same as with `Bars`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/talents.pl.md
> +1. zapisuje dowolną liczbę wartości dla określonego NPC (efektywnie rozszerzenie tablicy AIVar).
Lowercase letter at the start.
Also `efektywnie rozszerzenie`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/talents.pl.md
> +2. pozwala zidentyfikować NPC za pomocą unikalnego ID.
Lowercase letter at the start.

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/talents.pl.md
> +Znajduje pointer NPC o podanym ID.
`pointer`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/talents.pl.md
> +- `return` - pointer NPC
`pointer`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/talents.pl.md
> +- `return` - wartość, która jest później wykorzystywana jako Id talentu
`Id`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/trialoge.pl.md
> +## Zależnośći
`Zależnośći`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/trialoge.pl.md
> +Rozpoczyna zdefiniowany wczesniej ruch kamery.
`wczesniej`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/trialoge.pl.md
> +    AI_Output (other, self, "TRIA_TEST_03"); //I Mam ze sobą trochę złota, możemy się dogadać?
`//I Mam`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/trialoge.pl.md
> +6. **Hero:**    Napewno?
`Napewno`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/trialoge.pl.md
> +    // Bohater z owrotem rozmawia z Arto (self = Arto, other = Hero)
`owrotem`

2023-01-26 09:00 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/trialoge.pl.md
> +    AI_Output (other, self, "TRIA_TEST_05"); //Napewno?
`Napewno?`

2023-01-26 21:14 UTC, Emu-git commented on docs/zengin/scripts/extenders/lego/item_helper.pl.md
> +# ItemHelper
How can I translate ItemHelper to polish? Any sugestions?

2023-01-26 21:21 UTC, Emu-git commented on docs/zengin/scripts/extenders/lego/talents.pl.md
> +Znajduje pointer NPC o podanym ID.
How to translate it 
? "wskaźnik"?

2023-01-27 00:29 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/item_helper.pl.md
> +# ItemHelper
I wouldn't worry too much about it, "pomocnik do przedmiotów" is both correct and searchable. 
As for a more succinct version like "pomocnik przedmiotów" or "wspomagacz przedmiotowy" I feel like they're less searchable, don't roll of the tongue quite so easily.

2023-01-27 00:32 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/talents.pl.md
> +Znajduje pointer NPC o podanym ID.
I believe you've already translated it before as "wskaźnik" in another file, so yes, let's keep it the same.

2023-01-27 03:15 UTC, kamilkrzyskow requested changes

2023-01-27 03:15 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +    var int barLeft;    // Spacing bar - background left/right
Missed this before, translation missing. However, I don't understand this setting, so I can't help you with translation. Is this some margin / gap or the thickness of the bar border/frame 🤔

2023-01-28 22:12 UTC, Emu-git commented on docs/zengin/scripts/extenders/lego/trialoge.pl.md
> +6. **Hero:**    Napewno?
What's wrong here?

2023-01-28 22:26 UTC, Emu-git commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +    var int barLeft;    // Spacing bar - background left/right
I will ask Auronen about the meaning :stuck_out_tongue_winking_eye:

2023-01-28 22:53 UTC, kamilkrzyskow approved these changes

2023-01-28 22:54 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/trialoge.pl.md
> +6. **Hero:**    Napewno?
https://www.ortograf.pl/watpliwosci-jezykowe/jak-piszemy-na-pewno-czy-napewno-razem-czy-osobno

2023-01-29 10:18 UTC, kamilkrzyskow commented on docs/zengin/scripts/extenders/lego/bars.pl.md
> +    var int barLeft;    // Pasek odstępu - prawo/lewo tła
I'm not so sure about the word order, I also can't recommend anything better than
`Pasek odstępu tła - góra/dół`
`Pasek odstępu tła - lewo/prawo`
but this also isn't perfect 🤔

2023-01-29 10:18 UTC, kamilkrzyskow approved these changes

2023-01-29 10:29 UTC, kamilkrzyskow approved these changes

2023-01-29 12:37 UTC, merged

2023-01-29 13:38 UTC, kamilkrzyskow commented
All of the commits were squashed in eb886096481968812de326bed5d3927f009c708d